import { useRouter } from "next/router"
import Head from "next/head"
import Image from "next/image"
import { useMe } from "../lib/hooks"
import fetcher from "../lib/fetcher"

export default function Cv() {
  const { user, isLoading } = useMe()
  const router = useRouter()

  const handleSignout = async (event) => {
    event.preventDefault()
    // setIsLoading(true)

    let response = await fetcher("/signout")

    if (!response.error) {
      // setIsLoading(false)
      router.push("/")
    } else {
      console.log("Gick inte att logga ut")
      // setError("Wrong username or password")
      // setIsLoading(false)
    }
  }

  return (
    <div>
      <Head>
        <title>CV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>CV</h1>

        {!isLoading ? <p>User: {user?.username}</p> : <p>Loading...</p>}

        <button onClick={handleSignout}>Log out</button>
      </main>
    </div>
  )
}
